"""Small text surgery on instantiation statements and port lists.

All functions take and return the statement as a list of lines (template
text) and return ``None`` when the construct they need is not written in
the text (for example a pin generated by ``/*AUTOINST*/``).
"""

from __future__ import annotations

import re
from typing import Optional

_IDENT = r"[A-Za-z_][\w$]*"
_SKIP = re.compile(r"(?:\s+|//[^\n]*|/\*.*?\*/)*", re.S)      # whitespace and comments


def _match_paren(text: str, open_pos: int) -> Optional[int]:
    depth = 0
    i = open_pos
    quote = False
    while i < len(text):
        ch = text[i]
        if quote:
            if ch == "\\":
                i += 2
                continue
            if ch == '"':
                quote = False
        elif ch == '"':
            quote = True
        elif text.startswith("//", i):
            nl = text.find("\n", i)
            i = len(text) if nl < 0 else nl
            continue
        elif text.startswith("/*", i):
            end = text.find("*/", i + 2)
            i = len(text) if end < 0 else end + 2
            continue
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return None


def _conn_list(text: str) -> Optional[tuple[int, int]]:
    """(open, close) of the connection list: the last top-level ``( ... )``
    before the final ``;`` (skips ``#( ... )``)."""
    end = text.rfind(";")
    if end < 0:
        end = len(text)
    close = text.rfind(")", 0, end)
    if close < 0:
        return None
    depth = 0
    for i in range(close, -1, -1):
        ch = text[i]
        if ch == ")":
            depth += 1
        elif ch == "(":
            depth -= 1
            if depth == 0:
                return i, close
    return None


def _param_list(text: str) -> Optional[tuple[int, int]]:
    m = re.search(r"#\s*\(", text)
    if m is None:
        return None
    close = _match_paren(text, m.end() - 1)
    return (m.end() - 1, close) if close is not None else None


def _find_named(text: str, name: str, lo: int, hi: int) -> Optional[tuple[int, int, int]]:
    """(dot position, open paren, close paren) of ``.name( ... )`` in text[lo:hi]."""
    for m in re.finditer(r"\.\s*" + re.escape(name) + r"\b\s*\(", text[lo:hi]):
        dot = lo + m.start()
        op = lo + m.end() - 1
        cl = _match_paren(text, op)
        if cl is not None and cl <= hi:
            return dot, op, cl
    return None


def _find_implicit(text: str, name: str, lo: int, hi: int) -> Optional[tuple[int, int]]:
    """(start, end) of an implicit ``.name`` connection in text[lo:hi]."""
    for m in re.finditer(r"\.\s*" + re.escape(name) + r"\b", text[lo:hi]):
        end = lo + m.end()
        nxt = _SKIP.match(text, end).end()
        if nxt < len(text) and text[nxt] in ",)":
            return lo + m.start(), end
    return None


def rewrite_pin(lines: list[str], port: str, new_expr: str) -> Optional[list[str]]:
    """Replace the expression of ``.port( ... )`` in the connection list (an
    implicit ``.port`` becomes ``.port(new_expr)``)."""
    text = "\n".join(lines)
    span = _conn_list(text)
    if span is None:
        return None
    hit = _find_named(text, port, span[0], span[1])
    if hit is None:
        imp = _find_implicit(text, port, span[0], span[1])
        if imp is None:
            return None
        return (text[:imp[1]] + f"({new_expr})" + text[imp[1]:]).split("\n")
    _dot, op, cl = hit
    return (text[:op + 1] + new_expr + text[cl:]).split("\n")


def rewrite_param(lines: list[str], name: str, new_expr: str) -> Optional[list[str]]:
    """Replace the value of ``#( .name( ... ) )``."""
    text = "\n".join(lines)
    span = _param_list(text)
    if span is None:
        return None
    hit = _find_named(text, name, span[0], span[1])
    if hit is None:
        return None
    _dot, op, cl = hit
    return (text[:op + 1] + new_expr + text[cl:]).split("\n")


def remove_pin(lines: list[str], port: str) -> Optional[list[str]]:
    """Delete ``.port( ... )`` (or an implicit ``.port``) and one adjacent comma."""
    text = "\n".join(lines)
    span = _conn_list(text)
    if span is None:
        return None
    hit = _find_named(text, port, span[0], span[1])
    if hit is not None:
        start, end = hit[0], hit[2] + 1
    else:
        imp = _find_implicit(text, port, span[0], span[1])
        if imp is None:
            return None
        start, end = imp
    after = re.match(r"[ \t]*,[ \t]*(\n[ \t]*)?", text[end:])
    if after:
        end += after.end()
    else:
        before = re.search(r",[ \t]*(\n[ \t]*)?$", text[:start])
        if before:
            start = before.start()
    new = text[:start] + text[end:]
    # drop a line left empty by the removal
    return [ln for ln in new.split("\n") if ln.strip() or ln == ""]


def add_pins(lines: list[str], pins: list[tuple[str, str]]) -> Optional[list[str]]:
    """Add ``.port(expr)`` pins: before ``/*AUTOINST*/`` or ``.*`` when present,
    otherwise at the end of the connection list."""
    if not pins:
        return list(lines)
    text = "\n".join(lines)
    span = _conn_list(text)
    if span is None:
        return None
    op, cl = span
    inner = text[op + 1:cl]
    entries = [f".{p}({e})" for p, e in pins]
    m = re.search(r"/\*\s*AUTOINST\s*\*/|\.\*", inner)
    if m is not None:
        at = op + 1 + m.start()
        return (text[:at] + "".join(e + ", " for e in entries) + text[at:]).split("\n")
    body = inner.rstrip()
    if not body.strip():
        return (text[:op + 1] + ", ".join(entries) + text[cl:]).split("\n")
    last_nl = inner.rfind("\n", 0, len(body))
    if last_nl >= 0:
        # one pin per line: continue in the same layout
        line = inner[last_nl + 1:len(body)]
        indent = line[: len(line) - len(line.lstrip())]
        add = "".join(f",\n{indent}{e}" for e in entries)
    else:
        add = "".join(f", {e}" for e in entries)
    at = op + 1 + len(body)
    return (text[:at] + add + text[at:]).split("\n")


def subst_identifiers(expr: str, mapping: dict[str, str]) -> str:
    """Replace whole identifiers (not member names after ``.``) in *expr*."""
    def repl(m: "re.Match[str]") -> str:
        name = m.group(0)
        start = m.start()
        prev = expr[:start].rstrip()
        if prev.endswith(".") or prev.endswith("'") or prev.endswith("::"):
            return name
        return mapping.get(name, name)
    return re.sub(_IDENT, repl, expr)


def fold_constants(text: str) -> str:
    """Evaluate integer-only arithmetic inside ``[ ]`` and ``( )`` groups:
    ``[8-1:0]`` -> ``[7:0]``, ``(4*2)`` -> ``8``."""
    import ast

    def ev(s: str) -> Optional[str]:
        if not re.fullmatch(r"[\d\s+\-*()]+", s) or not re.search(r"\d", s):
            return None
        try:
            node = ast.parse(s.strip(), mode="eval")
        except SyntaxError:
            return None
        allowed = (ast.Expression, ast.BinOp, ast.UnaryOp, ast.Constant, ast.Add, ast.Sub, ast.Mult,
                   ast.USub, ast.UAdd)
        if not all(isinstance(n, allowed) for n in ast.walk(node)):
            return None
        val = eval(compile(node, "<dims>", "eval"), {"__builtins__": {}})  # noqa: S307 - ints only
        return str(val) if isinstance(val, int) else None

    def dims(m: "re.Match[str]") -> str:
        parts = m.group(1).split(":")
        out = []
        for p in parts:
            v = ev(p)
            out.append(v if v is not None else p)
        return "[" + ":".join(out) + "]"

    text = re.sub(r"\[([^\[\]]*)\]", dims, text)
    v = ev(text)
    return v if v is not None else text


def needs_parens(expr: str) -> bool:
    e = expr.strip()
    if re.fullmatch(_IDENT + r"(\s*\[[^\[\]]*\])*", e):
        return False
    if e.startswith("{") and e.endswith("}"):
        return False
    if e.startswith("(") and _match_paren(e, 0) == len(e) - 1:
        return False
    return bool(re.search(r"[-+*/%&|^~<>=?:]", e))


def full_select_base(expr: str, dims: str) -> Optional[str]:
    """``name`` when *expr* is ``name`` or ``name[<dims>]`` (the whole range)."""
    m = re.fullmatch(r"\s*(" + _IDENT + r")\s*(\[[^\[\]]*\])?\s*", expr)
    if m is None:
        return None
    if not m.group(2) or re.sub(r"\s+", "", m.group(2)) == re.sub(r"\s+", "", dims or ""):
        return m.group(1)
    return None


def port_list_span(text: str) -> Optional[tuple[int, int]]:
    """(open, close) of the ANSI port list in a module header text:
    ``module [lifetime] name [import ...;]... [#(...)] (...)``."""
    m = re.search(r"\bmodule\s+(?:(?:static|automatic)\s+)?" + _IDENT, text)
    if m is None:
        return None
    i = _SKIP.match(text, m.end()).end()
    while re.match(r"import\b", text[i:]):          # package imports in the header
        semi = text.find(";", i)
        if semi < 0:
            return None
        i = _SKIP.match(text, semi + 1).end()
    if text.startswith("#", i):                      # "#( ... )" parameter port list
        j = _SKIP.match(text, i + 1).end()
        if not text.startswith("(", j):
            return None
        close = _match_paren(text, j)
        if close is None:
            return None
        i = _SKIP.match(text, close + 1).end()
    if not text.startswith("(", i):
        return None
    cl = _match_paren(text, i)
    return (i, cl) if cl is not None else None
